// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbdsHPDTxjeEyU2Q_co5tIRZj7hVlSjw',
    appId: '1:684884749998:web:d420547ea05714304d073f',
    messagingSenderId: '684884749998',
    projectId: 'biztrack-5050e',
    authDomain: 'biztrack-5050e.firebaseapp.com',
    storageBucket: 'biztrack-5050e.firebasestorage.app',
    measurementId: 'G-PB3V41B6GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHyIPmv4L8UtcuXQIDiPe09yie1FJJLHY',
    appId: '1:684884749998:android:4d0d5f415e0c2c074d073f',
    messagingSenderId: '684884749998',
    projectId: 'biztrack-5050e',
    storageBucket: 'biztrack-5050e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVDSDkeQo7eIQfsDdtbZpiWneCVJqiz1Q',
    appId: '1:684884749998:ios:680e0ec756149f534d073f',
    messagingSenderId: '684884749998',
    projectId: 'biztrack-5050e',
    storageBucket: 'biztrack-5050e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVDSDkeQo7eIQfsDdtbZpiWneCVJqiz1Q',
    appId: '1:684884749998:ios:680e0ec756149f534d073f',
    messagingSenderId: '684884749998',
    projectId: 'biztrack-5050e',
    storageBucket: 'biztrack-5050e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfbdsHPDTxjeEyU2Q_co5tIRZj7hVlSjw',
    appId: '1:684884749998:web:46f628ebf101f32c4d073f',
    messagingSenderId: '684884749998',
    projectId: 'biztrack-5050e',
    authDomain: 'biztrack-5050e.firebaseapp.com',
    storageBucket: 'biztrack-5050e.firebasestorage.app',
    measurementId: 'G-ZGCXV3H17C',
  );
}
